# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ede03cccf78d72e11fb85a889fd95697d2ba40db6240e8b02038f063998bf1ca19e14f3ad6cc4900b611ac55d947b67b33d22936b32d7c121a2807de28fba715

test:
  secret_key_base: 623854f7d052ff0caf504c05fcbf6034872ed3b28032ad4f39382294a1ab250cbae3d6e15e5e0a18aba2e8ada0245b9682734b7a654afb368e6d40b031ecb668

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
